javascript-tutorial/zh.javascript.info

- 2-ui/1-document/11-coordinates/article.md
From [#321](https://github.com/xitu/javascript-tutorial-zh/issues/321)
经查找资料发现：
- 《JavaScript高级程序设计（第3版）》中 Attributes 译为“特性”
- 《JavaScript权威指南》中对 Attributes 有“特定的属性”的说法
做出以下小小的修改以提高阅读体验：
1. 添加译注
2. 把一些“Attributes”改为“特性”
>  添加译注区分attribute与property二词

- 1-js/11-async/08-async-await/01-rewrite-async/solution.md
- 1-js/11-async/08-async-await/01-rewrite-async/task.md
- 1-js/11-async/08-async-await/02-rewrite-async-2/solution.md
- 1-js/11-async/08-async-await/02-rewrite-async-2/task.md
- 1-js/11-async/08-async-await/03-async-from-regular/solution.md
- 1-js/11-async/08-async-await/03-async-from-regular/task.md
- 1-js/11-async/08-async-await/article.md
chapter: 1-js 11-async 08-async-await
> feat: translating 08-async-await

- 8-web-components/7-shadow-dom-events/article.md
-|-|-
article.md | [9ff7e2d](https://github.com/javascript-tutorial/en.javascript.info/commit/9ff7e2d2e58df3e1c92f76ffedc91356ffd8cfce) | 翻译
> Translate 8-web-components/7-shadow-dom-events/article.md

- 5-network/06-fetch-api/article.md
-|-|-
article.md | 1310171d| 新增翻译文件
> 5-network/06-fetch-api

- 1-js/99-js-misc/01-proxy/01-error-nonexisting/task.md
- 1-js/99-js-misc/01-proxy/02-array-negative/task.md
- 1-js/99-js-misc/01-proxy/03-observable/solution.md
- 1-js/99-js-misc/01-proxy/03-observable/task.md
- 1-js/99-js-misc/01-proxy/article.md
-|-|-
article.md | f12e89a | 翻译为中文
01-error-nonexisting/task.md | 8ab07e1 | 翻译为中文
02-array-negative/task.md | 52ef325 | 翻译为中文
03-observable/task.md | 763aba5 | 翻译为中文
03-observable/solution.md | 52ef325 | 翻译为中文
> translate  1-js/99-js-misc/01-proxy/article.md

- 1-js/05-data-types/03-string/1-ucfirst/solution.md
- 1-js/05-data-types/03-string/1-ucfirst/task.md
- 1-js/05-data-types/03-string/2-check-spam/solution.md
- 1-js/05-data-types/03-string/3-truncate/_js.view/test.js
- 1-js/05-data-types/03-string/3-truncate/solution.md
- 1-js/05-data-types/03-string/3-truncate/task.md
- 1-js/05-data-types/03-string/4-extract-currency/task.md
- 1-js/05-data-types/03-string/article.md
-|-|-
article.md | https://github.com/javascript-tutorial/en.javascript.info/commit/6f7ec123587f070ae1e16a11148135e604429324 | 更新译文
> Update translation of 1-js/05-data-types/03-string

- 1-js/09-classes/05-extend-natives/article.md
**目标章节**：1-js/09-classes/05-extend-natives
**当前上游最新 commit**：https://github.com/javascript-tutorial/en.javascript.info/commit/fcfef6a07842ed56144e04a80c3a24de049a952a
-|-|-
article.md | https://github.com/javascript-tutorial/en.javascript.info/commit/ad939bb80b49c06878916e7e05bd49380d67b5b4 | 更新译文
> Update translation of 1-js/09-classes/05-extend-natives

- 1-js/11-async/05-promise-api/article.md
**目标章节**：1-js/11-async/05-promise-api
**当前上游最新 commit**：https://github.com/javascript-tutorial/en.javascript.info/commit/36737518f826dbb3036db5eebcbe716184ff25a2
-|-|-
article.md | https://github.com/javascript-tutorial/en.javascript.info/commit/a53fb38c493771c1d2ccc4e2ef68690a072064fd | 更新译文
> Update translation of 1-js/11-async/05-promise-api

- 1-js/11-async/06-promisify/article.md
- 1-js/11-async/07-microtask-queue/article.md
**目标章节**：1-js/11-async/06-promisify and 07-microtask-queue
**当前上游最新 commit**：https://github.com/javascript-tutorial/en.javascript.info/commit/36737518f826dbb3036db5eebcbe716184ff25a2
-|-|-
1-js/11-async/06-promisify/article.md | https://github.com/javascript-tutorial/en.javascript.info/commit/1304aa12fcd4bd5e4c312ef43f63192382fa50bb | 更新译文
1-js/11-async/07-microtask-queue/article.md | https://github.com/javascript-tutorial/en.javascript.info/commit/837f7ab024e49cf99a9ffdab0126372d58cb1532 | 更新译文
> Update translation of 1-js/11-async/06-promisify and 07-microtask-queue

- 1-js/12-generators-iterators/2-async-iterators-generators/article.md
**目标章节**：1-js/12-generators-iterators/2-async-iterators-generators
**当前上游最新 commit**：https://github.com/javascript-tutorial/en.javascript.info/commit/c116813f9bde2336d4d8065ff9545e48ecb8ec25
-|-|-
article.md | https://github.com/javascript-tutorial/en.javascript.info/commit/88120708b185ee995c20080b14606fdc1c2565af | 更新译文
> Update translation of 1-js/12-generators-iterators/2-async-iterators-generators

- 2-ui/99-ui-misc/02-selection-range/article.md
**目标章节**：2-ui/99-ui-misc/02-selection-range
**当前上游最新 commit**：https://github.com/javascript-tutorial/en.javascript.info/commit/d84673a6ec1286c526d1ae4848d75e8b465684c9
-|-|-
article.md | https://github.com/javascript-tutorial/en.javascript.info/commit/7f26b917a085dc78f00c38b4a758c53ad2323fbd | 更新译文
> Update translation of 2-ui/99-ui-misc/02-selection-range

- 7-animation/2-css-animations/article.md
According to the [origin](https://github.com/javascript-tutorial/en.javascript.info/blob/master/7-animation/2-css-animations/article.md), it should be `4 properties to describe CSS transitions`.
> fix: fix typo in css-transition

- 1-js/11-async/03-promise-chaining/article.md
在 #更复杂的示例：fetch 这一小节的第一个示例代码中 alert(text) 是 JSON 格式，运行代码弹出框中 "isAdmin" 带有引号，但是注释没有
> 示例代码中的 JSON 格式错误

- 1-js/06-advanced-functions/06-function-object/article.md
Original in English: 
> The length property is sometimes used for introspection in functions that operate on other functions.
个人认为**运行时检查**比**内省**更容易让读者理解。另外链接改到了中文的维基百科。
---
**目标章节**：1-js/06-advanced-functions/06-function-object
-|-|-
article.md | 无 | 修改语句不通
> Fix: confusing translation sentence

- 8-web-components/7-shadow-dom-events/article.md
修正翻译错误，“显示设置”修正为“明确地设置”
**目标章节**：例如 8-web-components/7-shadow-dom-events/article.md
**当前上游最新 commit**：https://github.com/javascript-tutorial/zh.javascript.info/commit/a420010ddc553cc595c095665ef40952cd0d8a08
-|-|-
article.md | 无 | 修改翻译错误
> FIX: minor typo error in 8-web-components/7-shadow-dom-events/article.md

- 1-js/99-js-misc/01-proxy/article.md
**目标章节**：1-js/99-js-misc/01-proxy/article.md
> Fix: 将 trap 的翻译从「陷阱」改为「捕捉器」

- 1-js/11-async/08-async-await/article.md
**目标章节**：1-js/11-async/08-async-await
**当前上游最新 commit**：[065e31d](https://github.com/javascript-tutorial/en.javascript.info/commit/065e31d0d40bc81a87ff09450388f803a197a8f0#diff-03b9fb20d098766bb5b39b9dc0d6106c78ddca4b411e31b09eea6d021696c27c)
-|-|-
article.md | [065e31d](https://github.com/javascript-tutorial/en.javascript.info/commit/065e31d0d40bc81a87ff09450388f803a197a8f0#diff-03b9fb20d098766bb5b39b9dc0d6106c78ddca4b411e31b09eea6d021696c27c) | 参考上游增加部分说明
> UPD: update 1-js/11-async/08-async-await/article.md to 2021-03-19

- 1-js/05-data-types/03-string/article.md
我在阅读时觉得这几句有歧义，参考了MDN的描述才清晰。
-|-|-
> IMP: improve translation in 1-js/05-data-types/03-string/article.md

- 5-network/07-url/article.md
There's no need to emphasize that URL is a class. And, this saying is just weird.
没有必要强调 URL 是类。而且这种说法比较奇怪。比如我们一般不会说`人王二强`
-|-|-
> IMP: remove unnecessay character

- 9-regular-expressions/17-regexp-methods/article.md
- 调用 `regexp.exec(str)` 会返回第一个匹配项，并将紧随其后的位置保存在属性 `regexp.lastIndex` 中。
- 下一次同样的调用会从位置 `regexp.lastIndex` 开始搜索，返回下一个匹配项，并将其后的位置保存在 `regexp.lastIndex` 中。
- ...以此类推。
- 如果没有匹配项，则 `regexp.exec` 返回 `null`，并将 `regexp.lastIndex` 重置为 `0`。
排版小问题，无序列表中有两个 - 后面忘了空格，导致排版错误。
> fix: minor typo error in 9-regular-expressions/17-regexp-methods/article.md

- 2-ui/4-forms-controls/3-events-change-input/article.md
**目标章节**：2-ui/4-forms-controls/3-events-change-input
**当前上游最新 commit**：https://github.com/javascript-tutorial/en.javascript.info/commit/f4801c3a1705cf42372886c6f960c0b7e8f403bc
-|-|-
article.md | https://github.com/javascript-tutorial/en.javascript.info/commit/f4801c3a1705cf42372886c6f960c0b7e8f403bc | 增加安全限制说明 & 修改例子错误
同步上游内容。同时修复的例子错误可以关闭 #956
> feat: update translation of 2-ui/4-forms-controls/3-events-change-input/article.md

- 1-js/11-async/05-promise-api/article.md
**目标章节**： 1-js/11-async/05-promise-api
-|-|-
iterable 是名词，意为「可迭代的对象」。
英文释义：
> iterable: An iterable object such as an Array.
>
> ——[Promise.all() - JavaScript | MDN](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/all)
> feat: improve translation of "iterable" in 1-js/11-async/05-promise-api/article.md

- 1-js/07-object-properties/02-property-accessors/article.md
Getter ----->getter
**本 PR 所做更改如下：Getter ----->getter   将Getter修改为getter
-|-|-
> imp: 1-js/07-object-properties/02-property-accessors/article.md

- 4-binary/03-blob/article.md
本 PR 所做更改如下：
**目标章节**：4-binary/03-blob/article.md
**当前上游最新 commit**：[fb07094](https://github.com/javascript-tutorial/en.javascript.info/commit/fb070940efe331ff1c3b072d0fbfb38ddd39e6c5#diff-13fdcedd676c1e2ac8dd606d9b9fc923e2cd4716a2b1659f5cbeda02ee1cb653), [bf7eb9](https://github.com/javascript-tutorial/en.javascript.info/commit/bf7eb930350c16a6219e8dc55c90c6d3b1367bb2#diff-13fdcedd676c1e2ac8dd606d9b9fc923e2cd4716a2b1659f5cbeda02ee1cb653)
-|-|-
article.md | [fb07094](https://github.com/javascript-tutorial/en.javascript.info/commit/fb070940efe331ff1c3b072d0fbfb38ddd39e6c5#diff-13fdcedd676c1e2ac8dd606d9b9fc923e2cd4716a2b1659f5cbeda02ee1cb653) |  更新了 blob 到 arrayBuffer、blob 到流的最新方法 https://developer.mozilla.org/en-US/docs/Web/API/Blob/arrayBuffer …
> Update: 更新blob的最新使用方法

- 1-js/11-async/06-promisify/article.md
**目标章节**： 1-js/11-async/06-promisify
**当前上游最新 commit**：https://github.com/javascript-tutorial/en.javascript.info/commit/29216730a877be28d0a75a459676db6e7f5c4834
-|-|-
article.md | 无 | 修改一个翻译不通顺的地方
> fix: 修改 promisify 一章中不通顺的地方

- 9-regular-expressions/10-regexp-greedy-and-lazy/4-find-html-tags-greedy-lazy/task.md
**目标章节**：9-regular-expressions/10-regexp-greedy-and-lazy/4-find-html-tags-greedy-lazy
-|-|-
task.md | 无| 原文是Here we assume that tag attributes may not contain < and > (inside quotes too), that simplifies things a bit. 这里的翻译漏译了tag attributes
> fix: fix missing translation

- 1-js/06-advanced-functions/03-closure/article.md
**目标章节**：1-js/06-advanced-functions/03-closure/
-|-|-
> fix: translation of 1-js/06-advanced-functions/03-closure/

- 1-js/06-advanced-functions/06-function-object/article.md
**目标章节**：1-js/06-advanced-functions/06-function-object
-|-|-
article.md | 无 | 修改部分翻译
请做一下fact check, 我对JS还不是很熟悉.
> fix: 1-js/06-advanced-functions/06-function-object

- 2-ui/1-document/07-modifying-document/article.md
**目标章节**：2-ui/1-document/07-modifying-document
**当前上游最新 commit**：
-|-|-
里面还有个`[old]`, 我没找到在哪翻译.
> translate: 2-ui/1-document/07-modifying-document

- 1-js/99-js-misc/03-currying-partials/article.md
**目标章节**：例如 1-js/99-js-misc/03-currying-partials
**当前上游最新 commit**：-
变更理由和 #1116 相同，复制如下：
修正一个概念：“partially applied function”应当翻译成“部分应用函数”，而非“偏函数”。
部分应用函数（partially applied function）：对于一个函数f，“固定”某些参数，得到函数g，g就是f的部分应用函数，例如文中mul和double的例子。
偏函数（partial function）：指一个函数不是对于所有输入都有输出（返回值），与“全函数（total function）”相对应。
全函数（total function）：指一个函数对于所有输入，都有输出（返回值），而不会抛异常，无限循环等。
Reference：
[Partial functions - HaskellWiki](https://wiki.haskell.org/Partial_functions)
[Partial application - HaskellWiki](https://wiki.haskell.org/Partial_application)
-|-|-
article.md | 无 | “部分应用函数”不是“偏函数”
> 修正错误：“部分应用函数”不是“偏函数”

- 1-js/06-advanced-functions/10-bind/article.md
**目标章节**：1-js/06-advanced-functions/10-bind
**当前上游最新 commit**：-
修正一个概念：“partially applied function”应当翻译成“部分应用函数”，而非“偏函数”。  
部分应用函数（partially applied function）：对于一个函数f，“固定”某些参数，得到函数g，g就是f的部分应用函数，例如文中`mul`和`double`的例子。
偏函数（partial function）：指一个函数不是对于所有输入都有输出（返回值），与“全函数（total function）”相对应。
全函数（total function）：指一个函数对于所有输入，都有输出（返回值），而不会抛异常，无限循环等。
Reference：
[Partial functions - HaskellWiki](https://wiki.haskell.org/Partial_functions)
[Partial application - HaskellWiki](https://wiki.haskell.org/Partial_application)
-|-|-
article.md | 无 | 修正错误：部分应用函数不是偏函数
> fix: 部分应用函数不是偏函数

- 1-js/03-code-quality/01-debugging-chrome/article.md
> fix: translation of 1-js/03-code-quality/01-debugging-chrome/article.md

- 2-ui/99-ui-misc/02-selection-range/article.md
**目标章节**：[zh.javascript.info](https://github.com/javascript-tutorial/zh.javascript.info/tree/master)/[2-ui](https://github.com/javascript-tutorial/zh.javascript.info/tree/master/2-ui)/[99-ui-misc](https://github.com/javascript-tutorial/zh.javascript.info/tree/master/2-ui/99-ui-misc)/[02-selection-range](https://github.com/javascript-tutorial/zh.javascript.info/tree/master/2-ui/99-ui-misc/02-selection-range)/article.md
-|-|-
article.md | 无 | 修改打字错误
> fixed typo

- 2-ui/1-document/08-styles-and-classes/article.md
**目标章节**：[zh.javascript.info](https://github.com/javascript-tutorial/zh.javascript.info)/[2-ui](https://github.com/javascript-tutorial/zh.javascript.info/tree/master/2-ui)/[1-document](https://github.com/javascript-tutorial/zh.javascript.info/tree/master/2-ui/1-document)/[08-styles-and-classes](https://github.com/javascript-tutorial/zh.javascript.info/tree/master/2-ui/1-document/08-styles-and-classes)/article.md
**当前上游最新 commit**：https://github.com/javascript-tutorial/en.javascript.info/commit/24dfb1f30a7d9ed4e0a691cc3e93b329c562b4fa
-|-|-
article.md | 24dfb1f| Firefox 已经可以像 Chrome 一样显示
> Update from English Article

- 1-js/06-advanced-functions/02-rest-parameters-spread/article.md
**目标章节**：1-js/06-advanced-functions/02-rest-parameters-spread
**当前上游最新 commit**：https://github.com/javascript-tutorial/en.javascript.info/commit/733ff697c6c1101c130e2996f7eca860b2aa7ab9
文件名 | 参考 commit | 更改（理由）
-|-|-
article.md | 826260a | 修改过时的 `Object.assign()` 链接
> fix: outdated `Object.assign()` link

- 8-web-components/index.md
**目标章节**：8-web-components/index.md
**当前上游最新 commit**：https://github.com/javascript-tutorial/zh.javascript.info/commit/733ff697c6c1101c130e2996f7eca860b2aa7ab9
-|-|-
index.md | 无 | 
> feat: 8-web-components/index.md

- 1-js/05-data-types/05-array-methods/article.md
**目标章节**：1-js/05-data-types/05-array-methods
-|-|-
article.md | 无 | 补全缺失的 join 方法描述
> fix: join方法描述缺失

- 1-js/05-data-types/05-array-methods/8-sort-objects/solution.md
**目标章节**：1-js/05-data-types/05-array-methods/8-sort-objects
-|-|-
solution.md | 无 | 译注方法已写入正文，无需译注
> fix: delete outdated annotations

- 1-js/03-code-quality/06-polyfills/article.md
> fix(polyfills): core-js link

- 1-js/02-first-steps/12-nullish-coalescing-operator/article.md
**目标章节**：1-js/02-first-steps/12-nullish-coalescing-operator/article.md
**当前上游最新 commit**：https://github.com/javascript-tutorial/en.javascript.info/commit/c151e118ce74d921e1defd398018b4499e614fe8
-|-|-
`??` 和 `||` 优先级应该是 `3`，而不是 `4`，最新 MDN 截图信息如下所示：
> fix: update article.md

- 1-js/03-code-quality/06-polyfills/article.md
polyfill.io has been proven to be evil as it recently started implanting malicious scripts to jump to gambling sites.
https://blog.cloudflare.com/automatically-replacing-polyfill-io-links-with-cloudflares-mirror-for-a-safer-internet
**目标章节**：1-js/03-code-quality/06-polyfills
-|-|-
article.md | [141fc29](https://github.com/javascript-tutorial/zh.javascript.info/commit/141fc29091dd33c3ff36bfb4029a8453b36c4d73) | remove evil polyfill.io
> docs: remove polyfill.io

- 9-regular-expressions/07-regexp-escaping/article.md
-- | -- | --
article.md | 无 | 修正翻译
> fix: update translation
