javascript-tutorial/zh.javascript.info

- 1-js/03-code-quality/02-coding-style/1-style-errors/solution.md
- 1-js/03-code-quality/02-coding-style/1-style-errors/task.md
> 翻译 coding-style 中遗留的部分

- 1-js/03-code-quality/06-polyfills/article.md
> 1-js/03-code-quality/06-polyfills

- 1-js/05-data-types/11-json/1-serialize-object/task.md
- 1-js/05-data-types/11-json/2-serialize-event-circular/solution.md
- 1-js/05-data-types/11-json/2-serialize-event-circular/task.md
- 1-js/05-data-types/11-json/article.md
> 1 js/05 data types/11 json

- 1-js/05-data-types/06-iterable/article.md
> Iterables（可迭代对象）

- 1-js/07-object-oriented-programming/09-class/1-rewrite-to-class/task.md
- 1-js/07-object-oriented-programming/09-class/article.md
> 1 js/07 object oriented programming/09 class

- 1-js/07-object-oriented-programming/01-property-descriptors/article.md
- 1-js/07-object-oriented-programming/02-property-accessors/article.md
> 1-js/07-object-oriented-programming/01-property-descriptors and 02-property-accessors

- 1-js/02-first-steps/01-hello-world/article.md
Typo fix: forgot ` around tag.
> Fix article.md

- 1-js/02-first-steps/09-alert-prompt-confirm/article.md
1. 修正翻译（指出返回值是`null`）
2. 按照原文更新翻译
原文更改：https://github.com/iliakan/javascript-tutorial-en/commit/3a24621e7eb2e2476bb463f87eb0345447eb41b2#diff-25b0812e3f8822fea67b7279597e1d10R97
> Update and fix translation

- 2-ui/1-document/08-styles-and-classes/article.md
In line 296, the '六级' may should be corrected to ‘留意’ .
> Correct a wrong word

- 1-js/02-first-steps/14-function-basics/article.md
函数基础知识部分，“上述”一词误打为上诉，对该问题进行了修正
> fixed some statement errors

- 1-js/05-data-types/03-string/article.md
First argument of lastIndexOf should be a sub string
> Fix error of lastIndexOf

- 1-js/05-data-types/05-array-methods/8-sort-objects/solution.md
- 1-js/05-data-types/05-array-methods/8-sort-objects/task.md
closes https://github.com/javascript-tutorial/zh.javascript.info/issues/292
latest version: https://en.javascript.info/array-methods#sort-users-by-age
> feat(section-1.5.5.8): update task and solution

- 2-ui/1-document/07-modifying-document/article.md
[文档错误 #393](https://github.com/javascript-tutorial/zh.javascript.info/issues/393)
> Fix some errors (issue#393)

- 8-web-components/2-custom-elements/1-live-timer/solution.md
- 8-web-components/2-custom-elements/1-live-timer/solution.view/live-timer.js
- 8-web-components/2-custom-elements/1-live-timer/source.view/index.html
- 8-web-components/2-custom-elements/1-live-timer/source.view/live-timer.js
- 8-web-components/2-custom-elements/1-live-timer/task.md
- 8-web-components/2-custom-elements/article.md
参考了 MDN 的中文文档：https://developer.mozilla.org/zh-CN/docs/Web/Web_Components/Using_custom_elements，像 custom element，autonomous custom element 和 customized built-in element 大部分地方都是直接使用英文术语。在第一次提到的地方用括号标注了 MDN 上的中译名。如果有更好的处理方式，请在 review 意见提出。
> custom elements

- 2-ui/1-document/11-coordinates/article.md
修复一些格式错误。
Based on [issue398](https://github.com/javascript-tutorial/zh.javascript.info/issues/398)
Sync with upstream: [1591c8](https://github.com/javascript-tutorial/en.javascript.info/commit/1591c82a9cb5bbf4b1231d010a0f431e3b759e8f)
> 1-document-11-coordinates:fix some error

- .github/PULL_REQUEST_TEMPLATE.md
> feat:add pr template

- 1-js/02-first-steps/05-types/article.md
-|-|-
article.md | [d1190aa](https://github.com/javascript-tutorial/en.javascript.info/commit/d1190aae21d068ba8e9f219f96f5ccb289d39b8f)| 同步上游，修改部分错误
> Update: 1-js/02-first-steps/05-types

- 5-network/02-formdata/article.md
- 5-network/02-formdata/post.view/server.js
-|-|-
article.md | [5fbe4bd](https://github.com/javascript-tutorial/en.javascript.info/commit/5fbe4bdede617601fd31627988d9f11bc1dea106) | 新增文件并翻译
post.view/server.js | [b300836](https://github.com/javascript-tutorial/en.javascript.info/commit/b300836f00536a5eb9a716ad2cbb6b8fe97c25af) | 新增文件并翻译
> Update: 5-network/02-formdata

- 1-js/02-first-steps/06-type-conversions/article.md
-|-|-
article.md | [19223ae](https://github.com/javascript-tutorial/en.javascript.info/commit/19223ae762f03cdff4e83f6f963f4f427af93847) | 同步上游，修正部分错误
> Update: 1-js/02-first-steps/06-type-conversions

- 8-web-components/3-shadow-dom/article.md
-|-|-
article.md | 11b1671 | 翻译
> Translate web component shadow dom

- 6-data-storage/01-cookie/article.md
- 6-data-storage/01-cookie/cookie.js
-|-|-
article.md | 34e9cdc | 同步上游
cookie.js | 6fb4aab | 翻译
> Update: 6-data-storage/01-cookie

- 1-js/05-data-types/03-string/1-ucfirst/solution.md
- 1-js/05-data-types/03-string/article.md
-|-|-
article.md | 52ef325 | 同步修改
1-ucfirst/solution.md | 1b05095 | 同步修改
修复 #441
> Fix and sync upstream 1-js/05-data-types/03-string

- 1-js/02-first-steps/10-ifelse/2-check-standard/ifelse_task2.svg
你所看到的是一个 Pull Request 模板。（请删除此行，并请按实际情况修改下面内容，然后提交~）
ifelse_task2.svg | 9bfc8cf | 翻译成中文
> Translate into Chinese

- 1-js/05-data-types/03-string/article.md
-|-|-
article.md | 4856c06 | 修正字符编码中对单词 `back` 的翻译
> 修正字符编码中对单词 back 的翻译

- 1-js/05-data-types/02-number/article.md
参考 MDN：https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Equality_comparisons_and_sameness#%E5%90%8C%E5%80%BC%E7%9B%B8%E7%AD%89
-|-|-
article.md | 3640c38 | 翻译 `SameValue` 为同值相等，参考 MDN
> 翻译 SameValue 为同值相等

- 1-js/01-getting-started/3-code-editors/article.md
-|-|-
article.md | 382d4e513f987476cb054e5cca67bd79ec4e164c | 更新译文
> update 1-js / 01-getting-started / 3-code-editors

- 1-js/02-first-steps/16-javascript-specials/article.md
-|-|-
article.md | e9ded79 | 同步上游
> Update: 1-js/02-first-steps/16-javascript-specials

- 1-js/11-async/05-promise-api/article.md
-|-|-
article.md | 723514f | 修改Promise.allSettled的一处错误（英文版已单独提交PR）
> 修改一处有关Promise.allSettled的错误

- 9-regular-expressions/05-regexp-character-sets-and-ranges/1-find-range-1/solution.md
-|-|-
solution.md | 174493d | 修改部分错误
> 集合和范围：修正错误

- 4-binary/02-text-decoder/article.md
-|-|-
article.md | bc4d667 | 翻译原文
> TextDecoder and TextEncoder translate

- 1-js/12-generators-iterators/2-async-iterators-generators/article.md
- 1-js/12-generators-iterators/2-async-iterators-generators/head.html
translation ver 1
-|-|-
article.md |  9f158f9a| 新增翻译文件
head.html|5bca8a5e| 新增翻译文件
> async-iterators-generators

- 1-js/09-classes/05-extend-natives/article.md
-|-|-
article.md | ad939bb8| 新增翻译文件
> 05-extends-natives

- 1-js/09-classes/05-extend-natives/article.md
你所看到的是一个 Pull Request 模板。（请删除此行，并请按实际情况修改下面内容，然后提交~）
-|-|-
article.md | 6d0fef0 | minor changes
> minor change: revert // 程序错误提示 (非注释）to english

- 5-network/06-fetch-api/article.md
-|-|-
article.md | 1310171 | 修改标点错误
> [fix]5-network/06-fetch-api

- 2-ui/99-ui-misc/01-mutation-observer/article.md
-|-|-
article.md | [f0e848a](https://github.com/javascript-tutorial/en.javascript.info/commit/f0e848ad68188c37bf8aca0129b946e5de604286) | 新增翻译文件
> 2-ui/99-ui-misc/01-mutation-observer/

- 1-js/03-code-quality/06-polyfills/article.md
-|-|-
article.md | https://github.com/javascript-tutorial/en.javascript.info/commit/d4c9b1ab97de8169a7f9a78b2ca2300e0796ce76 | 更新译文
> Update translation of 1-js/03-code-quality/06-polyfills/article.md 

- 2-ui/99-ui-misc/02-selection-range/article.md
-|-|-
article.md | [fd215a4](https://github.com/javascript-tutorial/en.javascript.info/commit/fd215a40d21b947961aa0b4bd9428cb3fb8e5f5f) | 新增翻译文件
> 2-ui/99-ui-misc/02-selection-range/

- 9-regular-expressions/06-regexp-boundary/1-find-time-hh-mm/solution.md
- 9-regular-expressions/06-regexp-boundary/article.md
-|-|-
article.md | [fc0b185](https://github.com/javascript-tutorial/en.javascript.info/commit/fc0b185) | 新增翻译
1-find-time-hh-mm/solution.md|[fc0b185](https://github.com/javascript-tutorial/en.javascript.info/commit/fc0b185)|新增翻译
> 9-regular-expressions/06-regexp-boundary/

- 9-regular-expressions/03-regexp-unicode/article.md
-|-|-
article.md | 566b67d | 新增翻译
> Finished translation for article regexp-unicode

- 1-js/08-prototypes/04-prototype-methods/article.md
-|-|-
article.md | b7c20c3| 拼写错误
> typo: seeters -> setters

- 1-js/05-data-types/07-map-set/article.md
你所看到的是一个 Pull Request 模板。（请删除此行，并请按实际情况修改下面内容，然后提交~）
-|-|-
limitations.png | [85e67eb](https://github.com/javascript-tutorial/en.javascript.info/commit/85e67ebb5bc491b3a2de9f1a6b38829af8c94ee5) | 增改新翻译，修正一些格式问题
> 1-js/05-data-types/07-map-set/

- 1-js/05-data-types/07-map-set/article.md
**目标章节**：1-js/05-data-types/07-map-set
**当前上游最新 commit**：
-|-|-
article.md |  | 更新译文
> Update translation of 1-js/05-data-types/07-map-set

- 1-js/06-advanced-functions/05-global-object/article.md
**目标章节**：1-js/06-advanced-functions/05-global-object
**上游最新 commit**：https://github.com/javascript-tutorial/en.javascript.info/commit/405150f1f286db19a3c1ed913fa3e905fcefbe46
-|-|-
article.md | https://github.com/javascript-tutorial/en.javascript.info/commit/a736f71fb4aa2aeff52f3ce933b84d2ca169cbe4 | 更新译文
> Update translation of 1-js/06-advanced-functions/05-global-object

- 1-js/07-object-properties/02-property-accessors/article.md
**目标章节**：1-js/07-object-properties/02-property-accessors
**当前上游最新 commit**：https://github.com/javascript-tutorial/en.javascript.info/commit/fcfef6a07842ed56144e04a80c3a24de049a952a
-|-|-
article.md | https://github.com/javascript-tutorial/en.javascript.info/commit/4489949ed4c77be810b3ae547f7e23136c2b6df0 | 更新译文
> Update translation of 1-js/07-object-properties/02-property-accessors

- 1-js/09-classes/02-class-inheritance/1-class-constructor-error/solution.md
- 1-js/09-classes/02-class-inheritance/2-clock-class-extended/solution.md
- 1-js/09-classes/02-class-inheritance/2-clock-class-extended/task.md
- 1-js/09-classes/02-class-inheritance/3-class-extend-object/solution.md
- 1-js/09-classes/02-class-inheritance/3-class-extend-object/task.md
- 1-js/09-classes/02-class-inheritance/article.md
**目标章节**：1-js/09-classes/02-class-inheritance
**当前上游最新 commit**：https://github.com/javascript-tutorial/en.javascript.info/commit/fcfef6a07842ed56144e04a80c3a24de049a952a
-|-|-
article.md | https://github.com/javascript-tutorial/en.javascript.info/commit/c72cca89d5a56c5a5ace451c05bb3b90077a71e8 | 更新译文
> Update translation of 1-js/09-classes/02-class-inheritance

- 1-js/09-classes/06-instanceof/1-strange-instanceof/solution.md
- 1-js/09-classes/06-instanceof/1-strange-instanceof/task.md
- 1-js/09-classes/06-instanceof/article.md
**目标章节**：1-js/09-classes/06-instanceof
**当前上游最新 commit**：https://github.com/javascript-tutorial/en.javascript.info/commit/fcfef6a07842ed56144e04a80c3a24de049a952a
-|-|-
article.md | https://github.com/javascript-tutorial/en.javascript.info/commit/028b408c297c75c9f3010f8aa91091c63177769a | 更新译文
> Update translation of  1-js/09-classes/06-instanceof

- 1-js/02-first-steps/01-hello-world/1-hello-alert/index.html
- 1-js/02-first-steps/01-hello-world/1-hello-alert/solution.md
- 1-js/04-object-basics/01-object/3-is-empty/solution.md
> Update solution.md and solution.js files for many tasks

- 2-ui/1-document/07-modifying-document/article.md
**目标章节**：2-ui/1-document/07-modifying-document 
**当前上游最新 commit**：https://github.com/javascript-tutorial/en.javascript.info/commit/3086efea77c9a5f05dbc9dd3c0a02ae9fcb95adc
-|-|-
article.md | https://github.com/javascript-tutorial/en.javascript.info/commit/2ddea5dad65bb4c6732a8d4086722e6485360efe | 更新译文
> Update translation of 2-ui/1-document/07-modifying-document

- 2-ui/2-events/04-default-browser-action/article.md
- 2-ui/2-events/05-dispatch-events/article.md
**目标章节**：2-ui/2-events/05-dispatch-events
**当前上游最新 commit**：https://github.com/javascript-tutorial/en.javascript.info/commit/162280b6d238ce32bbd8ff7a3f7992be82c2311a
-|-|-
article.md | https://github.com/javascript-tutorial/en.javascript.info/commit/484b24de37d8bdff33365a62df3e7c242d1145eb | 更新译文
> Update translation of 2-ui/2-events/05-dispatch-events

- 2-ui/5-loading/01-onload-ondomcontentloaded/article.md
**目标章节**：2-ui/5-loading/01-onload-ondomcontentloaded
**当前上游最新 commit**：https://github.com/javascript-tutorial/en.javascript.info/commit/2a6e87a6e9aae902cbcd5f870982d99e3da6cb2f
-|-|-
article.md | https://github.com/javascript-tutorial/en.javascript.info/commit/958cbe72b89e96a5bf75df0166b0bfd50f10ccd1 | 更新译文
> Update translation of 2-ui/5-loading/01-onload-ondomcontentloaded

- 1-js/02-first-steps/01-hello-world/article.md
- 1-js/02-first-steps/13-switch/article.md
- 1-js/02-first-steps/17-javascript-specials/article.md
- 1-js/04-object-basics/01-object/article.md
- 1-js/04-object-basics/04-object-methods/2-check-syntax/solution.md
- 1-js/04-object-basics/04-object-methods/3-why-this/solution.md
- 1-js/05-data-types/02-number/article.md
- 1-js/06-advanced-functions/01-recursion/article.md
- 1-js/06-advanced-functions/02-rest-parameters-spread/article.md
- 1-js/06-advanced-functions/03-closure/article.md
- 1-js/08-prototypes/04-prototype-methods/article.md
- 1-js/09-classes/01-class/article.md
- 1-js/99-js-misc/03-currying-partials/article.md
- 2-ui/1-document/11-coordinates/1-find-point-coordinates/solution.md
- 2-ui/2-events/02-bubbling-and-capturing/article.md
- 2-ui/2-events/04-default-browser-action/article.md
- 2-ui/2-events/05-dispatch-events/article.md
- 2-ui/4-forms-controls/1-form-elements/article.md
- 2-ui/5-loading/03-onload-onerror/article.md
> Update 04-05 in en-comparison

- 4-binary/03-blob/article.md
**目标章节**：4-binary/03-blob
**当前上游最新 commit**：https://github.com/javascript-tutorial/en.javascript.info/commit/c89ddc5d92195e08e2c32e30526fdb755fec4622
-|-|-
article.md | https://github.com/javascript-tutorial/en.javascript.info/commit/9f5d7bab569bcc603ae9916f0d64b0ad3619d077 | 更新译文
> Update translation of 4-binary/03-blob

- 5-network/01-fetch/01-fetch-users/solution.md
- 5-network/01-fetch/01-fetch-users/task.md
- 5-network/02-formdata/article.md
**目标章节**：5-network/02-formdata and etc.
**当前上游最新 commit**：https://github.com/javascript-tutorial/en.javascript.info/commit/c89ddc5d92195e08e2c32e30526fdb755fec4622
-|-|-
article.md | https://github.com/javascript-tutorial/en.javascript.info/commit/35ff499b9237c1c7588ff2799f2a524d3223b0b7 | 更新译文
> Update translation of 5-network/02-formdata and etc.

- 5-network/08-xmlhttprequest/article.md
- README.md
**目标章节**：5-network/08-xmlhttprequest
**当前上游最新 commit**：https://github.com/javascript-tutorial/en.javascript.info/commit/2a0142479771ede368aab6829c40f18c49afa5f5
-|-|-
article.md | https://github.com/javascript-tutorial/en.javascript.info/commit/a88e082ef9065bcf1e9d6556a564eaade8888df8 | 更新译文
> Update README and translation of 5-network/08-xmlhttprequest

- 1-js/10-error-handling/1-try-catch/article.md
> Correct translation article.md

- 1-js/05-data-types/12-json/article.md
目标章节：1-js/05-data-types/12-json/article.md
> Fix minor typo error

- 5-network/05-fetch-crossorigin/article.md
- 5-network/07-url/article.md
- 5-network/11-websocket/article.md
**目标章节**：
5-network/05-fetch-crossorigin
5-network/07-url
5-network/11-websocket
-|-|-
article.md | 无| 修改部分错误
article.md | 无| 修改部分错误
article.md | 无| 修改部分错误
> Fix some typo error

- 1-js/02-first-steps/15-function-basics/article.md
- 1-js/02-first-steps/18-javascript-specials/article.md
- 1-js/03-code-quality/05-testing-mocha/beforeafter.view/test.js
**基于：** #766 
这是后续修补的其中一部分，编号 1
1. 1-js/02-first-steps/15-function-basics/article.md
2. 1-js/02-first-steps/18-javascript-specials/article.md
3. 1-js/03-code-quality/05-testing-mocha/beforeafter.view/test.js
> Update translation related to PR-766, Part-1

- 1-js/02-first-steps/06-alert-prompt-confirm/article.md
基于 [Update some charactors from upstream to [Jun 28, 2020] Part-1](https://github.com/javascript-tutorial/zh.javascript.info/pull/764)
**目标章节**：1-js/02-first-steps/06-alert-prompt-confirm/article.md 
> Update translation related to PR-764, Part-1

- 5-network/05-fetch-crossorigin/article.md
- 5-network/11-websocket/article.md
- 6-data-storage/01-cookie/article.md
- 6-data-storage/03-indexeddb/article.md
Update some chapters to [Jul 17, 2020] Part-7
**本 PR 为从上游同步更新的 Part 5，需要管理员认领翻译，方式如下：**
1. Review 本 PR，没问题则将其 merge。
2. 根据本 PR 的 Files changed，找出这几个文件中所需要翻译的句子和段落。新建自己的分支，对这些内容进行翻译，并提交新的 PR。
3. 在提交的新 PR 中，要关联本 PR。
4. 所提交的新 PR，要将本 PR 所修改的文件中，所有需要翻译的部分均翻译完成。
5. 所提交的新 PR，需要像正常 PR 那样，经过校对 -> 修改 -> 审核的流程。
> Update some chapters to [Jul 17, 2020] Part-7

- 1-js/02-first-steps/05-types/article.md
- 1-js/02-first-steps/06-alert-prompt-confirm/article.md
- 1-js/02-first-steps/10-ifelse/article.md
- 1-js/02-first-steps/12-nullish-coalescing-operator/article.md
- 1-js/03-code-quality/02-coding-style/1-style-errors/solution.md
- 1-js/04-object-basics/03-garbage-collection/article.md
- 1-js/04-object-basics/07-optional-chaining/article.md
- 1-js/04-object-basics/08-symbol/article.md
- 1-js/04-object-basics/09-object-toprimitive/article.md
- 1-js/06-advanced-functions/03-closure/7-let-scope/solution.md
- 1-js/06-advanced-functions/09-call-apply-decorators/04-throttle/task.md
- 1-js/06-advanced-functions/10-bind/article.md
- 1-js/08-prototypes/04-prototype-methods/article.md
- 1-js/09-classes/06-instanceof/article.md
- 1-js/10-error-handling/1-try-catch/article.md
- 1-js/11-async/04-promise-error-handling/article.md
- 1-js/99-js-misc/01-proxy/01-error-nonexisting/task.md
- 1-js/99-js-misc/01-proxy/article.md
- 2-ui/1-document/07-modifying-document/article.md
- 2-ui/2-events/05-dispatch-events/article.md
- 2-ui/3-event-details/1-mouse-events-basics/article.md
- 2-ui/3-event-details/4-mouse-drag-and-drop/ball.view/index.html
- 3-frames-and-windows/03-cross-window-communication/sandbox.view/index.html
- 5-network/05-fetch-crossorigin/article.md
- 5-network/07-url/article.md
- 6-data-storage/02-localstorage/article.md
> Update from upstream july commit 4583

- 1-js/08-prototypes/04-prototype-methods/3-compare-calls/solution.md
> Fix minor typo error of 1-js/08-prototypes/04-prototype-methods/3-compare-calls/solution.md

- 1-js/11-async/05-promise-api/article.md
Fix minor typo error in 1-js/11-async/05-promise-api/article.md
> Fix minor typo error in 1-js/11-async/05-promise-api/article.md

- 1-js/09-classes/05-extend-natives/article.md
**目标章节**：1-js/09-classes/05-extend-natives
**当前上游最新 commit**：`50680d4`
-|-|-
article.md | 564cc0d| 修改部分错误
> fix: extend-natives

- 1-js/10-error-handling/1-try-catch/article.md
Related PR: https://github.com/javascript-tutorial/zh.javascript.info/pull/794
> ADD: translation of some sentences

- 1-js/13-modules/02-import-export/article.md
- 8-web-components/2-custom-elements/article.md
**目标章节**：8-web-components/2-custom-elements/article.md
-|-|-
article.md | 无 | 更改中文错别字
> 8-web-components/2-custom-elements

- 4-binary/01-arraybuffer-binary-arrays/article.md
**目标章节**：4-binary/01-arraybuffer-binary-arrays/
**当前上游最新 commit**：[fc3f811](https://github.com/javascript-tutorial/en.javascript.info/commit/fc3f811c03ca97ff8304271bb2b918413bed720f)
|文件名|参考上游 commit|更改（理由）|
| ---- | ---- | ---- |
|article.md|[193e174](https://github.com/javascript-tutorial/en.javascript.info/commit/193e174653324cdaf037bef488994d65981fb4b4)|修改翻译错误|
> FIX: fix translation errors

- 1-js/05-data-types/07-map-set/article.md
添加遗漏文字
**目标章节**：1-js/05-data-types/07-map-set/
**当前上游最新 commit**：[f6ae0b5](https://github.com/javascript-tutorial/en.javascript.info/commit/f6ae0b5a5f3e48074312ca3e47c17c92a5a52328)
-|-|-
article.md | 无 | 添加遗漏文字
> 修复 1-js/05-data-types/07-map-set/article.md 文字遗漏

- 2-ui/1-document/07-modifying-document/article.md
**目标章节**：2-ui/1-document/07-modifying-document
**当前上游最新 commit**：[9e52cf3](https://github.com/javascript-tutorial/en.javascript.info/commit/9e52cf3e14b90daf9799fac1af50da5166890b15)
-- | -- | --
article.md | 无 | 错别字修正
> FIX: fix minor typo error in 2-ui/1-document/07-modifying-document/article.md

- 1-js/11-async/05-promise-api/article.md
> IMP: improve translation in 1-js/11-async/05-promise-api/article.md

- 3-frames-and-windows/06-clickjacking/article.md
fix typos
**目标章节**：3-frames-and-windows/06-clickjacking
修改翻译错别字
> FIX: fix typo error in 3-frames-and-windows/06-clickjacking/article.md

- 5-network/11-websocket/article.md
Correct translation typos
**目标章节**：5-network/11-websocket
修正翻译错误
> FIX: fix minor typo error in 5-network/11-websocket/article.md

- 2-ui/1-document/04-searching-elements-dom/article.md
**目标章节**：2-ui/1-document/04-searching-elements-dom
**当前上游最新 commit**：29f0121b1c08759b4ae8531bd356771fba0dc8b0
2-ui/1-document/04-searching-elements-dom/article.md | 无 | 缺字及个别翻译
> IMP: translation of 2-ui/1-document/04-searching-elements-dom

- 8-web-components/5-slots-composition/article.md
fix translation errors
**目标章节**：8-web-components/5-slots-composition
修正机翻
> IMP: translation of 8-web-components/5-slots-composition

- 9-regular-expressions/01-regexp-introduction/article.md
**目标章节**： 9-regular-expressions\01-regexp-introduction
**当前上游最新 commit**：https://github.com/javascript-tutorial/en.javascript.info/commit/7c73f64a1381ad212843e22d356f7e134c59c821
-|-|-
article.md | 无 | 修改文章链接错误
> FIX: article link error

- 9-regular-expressions/11-regexp-groups/article.md
**目标章节**：9-regular-expressions/11-regexp-groups/
-|-|-
article.md | 无 | 修改语句错误
> fix: 删除 9-regular-expressions/11-regexp-groups/article.md 中多余英文原文

- 1-js/02-first-steps/15-function-basics/article.md
fix: '表格' -> '表单'
**目标章节**：1-js/02-first-steps/15-function-basics/article.md
**本 PR 所做更改如下：
fix: '表格' -> '表单'
-|-|-
> fix: 1-js/02-first-steps/15-function-basics/article.md createForm(..)      // 创建表单

- 1-js/99-js-misc/01-proxy/article.md
**目标章节**：1-js/99-js-misc/01-proxy/article.md
文件名 | 更改（理由）
-|-
article.md | 翻译表述问题
> fix: 1-js/99-js-misc/01-proxy/article.md 优化翻译

- 5-network/06-fetch-api/article.md
**目标章节**：5-network/06-fetch-api/article.md
**当前上游最新 commit**：8d04d0d2db97276dbb2b451c30a7bd3e05d65831
-|-|-
article.md | 无 | 修改翻译手误
> fix: typo error in 5-network/06-fetch-api/article.md

- 2-ui/1-document/04-searching-elements-dom/article.md
**目标章节**：2-ui/1-document/04-searching-elements-dom/
**当前上游最新 commit**：
-|-|-
article.md | 无 | 翻译错误，原文中的 over 应该是 **在...之上**，而不是 **结束**
> fix: translation

- 8-web-components/5-slots-composition/article.md
> fix: querySelectorAll in 8-web-components/5-slots-composition/article.md

- 1-js/12-generators-iterators/2-async-iterators-generators/article.md
> FIX: fix bug caused by GitHub data change

- 1-js/12-generators-iterators/2-async-iterators-generators/article.md
> fix: bug caused by GitHub data change

- 1-js/11-async/05-promise-api/article.md
文件名 | 参考上游 commit | 更改（原因）
-|-|-
article.md |无 | Promise 缺少 any 静态方法
> pr issues/1000  feat: add promise.any

- 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
**目标章节**：regexp lookahead lookbehind
**当前上游最新 commit**：`2cca9a9`
-|-|-
article.md | 无| 去除多余的符号；修改半角为全角符号
> fix: improper symbol

- 9-regular-expressions/16-regexp-sticky/article.md
> 补充 ** 完成 Markdown Bold 展示

- 1-js/05-data-types/03-string/article.md
Fix clerical error at line 603.
-|-|-
> fix: Clerical error

- 5-network/09-resume-upload/article.md
> fix(network/resume-upload): typo

- 2-ui/5-loading/02-script-async-defer/article.md
**目标章节**：例如 2-ui/05-loading/02-scripts-async-defer
-|-|-
article.md | 4cf9f5a | 修改typo
> fix(typo): fix type in async & defer

- 1-js/02-first-steps/17-arrow-functions-basics/article.md
> fix: typo error

- 1-js/02-first-steps/17-arrow-functions-basics/article.md
[zh.javascript.info/1-js/02-first-steps/17-arrow-functions-basics](https://github.com/javascript-tutorial/zh.javascript.info/tree/master/1-js/02-first-steps/17-arrow-functions-basics)
<br/>
修改了sample code中的一处语句错误，详见commit。
纠正后的sample code就能与英文原文的sample code完全一致了，且英文原文的该sample code是正确的。
<br/>
无，上游无需改动，因为该PR的目的正在于修改该汉译版文章的错误，以使其与英文原文一致。
<br/>
> Fix bug: sample code

- 1-js/05-data-types/12-json/article.md
修复错别字
**目标章节**：1-js/05-data-types/12-json
**当前上游最新 commit**：[8536bca](https://github.com/javascript-tutorial/en.javascript.info/commit/8536bca288b12653a9dd28c021b870f771e370c6)
-|-|-
article.md | 无 | 修复错别字
> fix: 解构->结构

- 1-js/13-modules/01-modules-intro/article.md
**目标章节**：例如 1-js/13-modules/01-modules-intro
-|-|-
article.md | a23882d | 去掉重复文案
`设置`两个字重复了两遍，查看英文版后发现确实是重复了~
> fix: translation in 1-js/13-modules/01-modules-intro/article.md

- 1-js/04-object-basics/07-optional-chaining/article.md
> fix: typo in 1-js/04-object-basics/07-optional-chaining/article.md

- 1-js/11-async/02-promise-basics/article.md
**目标章节**：例如 1-js/11-async/02-promise-basics/
-|-|-
article.md | 无 | Typo
> Fix: 1-js/11-async/02-promise-basics/

- 1-js/13-modules/01-modules-intro/article.md
**目标章节**：1-js/13-modules/01-modules-intro
-|-|-
“That said” 的翻译好像不太对?
> fix: 1-js/13-modules/01-modules-intro/

- 1-js/13-modules/02-import-export/article.md
**目标章节**：1-js/13-modules/02-import-export
-|-|-
> fix: 1-js/13-modules/02-import-export

- 5-network/04-fetch-abort/article.md
**目标章节**：例如 5-network/04-fetch-abort/article.md
-|-|-
article.md | 无 | 修改部分描述
> feat: improve translation 5-network/04-fetch-abort/article.md

- 1-js/05-data-types/05-array-methods/article.md
> Fix name error

- 1-js/09-classes/01-class/article.md
**目标章节**：1-js/09-classes/01-class
**当前上游最新 commit**：https://github.com/javascript-tutorial/en.javascript.info/commit/53b35c16835b7020a0a5046da5a47599d313bbb8
-|-|-
> fix wrong text

- 2-ui/1-document/06-dom-attributes-and-properties/article.md
这里是alert打印的内容，不应该翻译
something="non-standard"
-|-|-
> typo: 这里是alert打印的内容

- 5-network/06-fetch-api/article.md
> typo: 语句改的更通顺些

- 2-ui/1-document/11-coordinates/article.md
**目标章节**：例如 2-ui/1-document/11-coordinates
-|-|-
article.md | 无| “to show”应当翻译为“展示”。“展示”和“显示”相比，更能体现人“主动”修改页面、呈现新元素的意思。
> feat: update translation

- 1-js/02-first-steps/08-operators/article.md
**目标章节**：1-js/02-first-steps/08-operators
**当前上游最新 commit**：https://github.com/javascript-tutorial/en.javascript.info/commit/5dff42ba283bce883428c383c080fa9392b71df8
-|-|-
> feat: remove the extra ')'

- 9-regular-expressions/11-regexp-groups/article.md
close: https://github.com/javascript-tutorial/zh.javascript.info/issues/1138
> fix: update regexp-groups

- 4-binary/03-blob/article.md
**目标章节**：例如 4-binary/03-blob/article.md
**当前上游最新 commit**：https://github.com/javascript-tutorial/zh.javascript.info/commit/e2dc344d9d1e6460ac0ad913138300c863d77500
-|-|-
4-binary/03-blob/article.md | 无 | 修改拼写错误
> fix: blob spell

- 2-ui/4-forms-controls/2-focus-blur/article.md
> fix: Update article.md

- 1-js/04-object-basics/08-symbol/article.md
> fix: that said 翻译

- 1-js/02-first-steps/13-while-for/article.md
> Fix anchor name

- 2-ui/1-document/02-dom-nodes/article.md
**目标章节**：例如 2-ui/1-document/02-dom-nodes
-|-|-
article.md | 无 | 修复了打开 elk.html  页面丢失的问题
> fix: Fixed the problem that elk.html could not be opened

- 1-js/01-getting-started/3-code-editors/article.md
> fix: WebStorm licence
